name = "Silverton"
uuid = "0bec08f2-0762-458b-81bf-8c70dd8945e7"
authors = ["ethan <ethanrussell77@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]